version: "2"

run:
  timeout: 5m
  tests: false
  concurrency: 4
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - mocks
  exclude-dirs-use-default: true
  exclude-files:
    - _test\.go$
    - _mock\.go$

formatters:
  enable:
    - gofmt
    - goimports
    - golines

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - unused
    - misspell
    - revive
    - gosec
    - goconst
    - gocyclo
    - gocritic
    - bodyclose
    - prealloc
    - rowserrcheck
    - prealloc
    - unparam
    - nolintlint
    - makezero
    - whitespace
    - asciicheck
    - wastedassign
    - durationcheck
    - nakedret
    - nilerr
    - sloglint

linters-settings:
  revive:
    rules:
      - name: exported
        arguments: [ { checkExported: true } ]
      - name: package-comments
      - name: var-naming
        arguments: [ { allowCommonInitialisms: true } ]
      - name: indent-error-flow
      - name: error-strings
      - name: error-return
      - name: blank-imports
      - name: context-as-argument
      - name: if-return
      - name: naked-return
      - name: predeclared
      - name: range-val-copy
      - name: typecheck
      - name: unnecessary-else
  gocyclo:
    min-complexity: 10
  gocritic:
    enabled-tags:
      - performance
      - style
      - opinionated
    settings:
      rangeValCopy:
        warnSize: 128
      hugeParam:
        warnSize: 80
  govet:
    enable:
      - fieldalignment
      - lostcancel
  golines:
    max-len: 120