version: '2'

run:
  timeout: 5m
  issues-exit-code: 2
  tests: false
  concurrency: 4

linters:
  enable:
    - bodyclose
    - lll
    - dupl
    - goconst
    - gocyclo
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - unparam
  settings:
    lll:
      line-length: 120
      tab-width: 1
    goconst:
      min-occurrences: 10
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: indent-error-flow
        - name: error-strings
        - name: error-return
        - name: blank-imports
        - name: context-as-argument
        - name: if-return
        - name: unused-parameter
          severity: warning
          disabled: false
        - name: unexported-return
          severity: error
          disabled: false
    dupl:
      threshold: 200 # TODO - adjust this value based
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
    nakedret:
      max-func-lines: 50
    unparam:
      check-exported: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
        - opinionated
      settings:
        hugeParam:
          sizeThreshold: 512
