name: Setup Go
description: Sets up Go with caching for optimal performance
inputs:
  go-version:
    description: Version of Go to install
    required: false
    default: "1.23"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
    
    - name: Download dependencies
      shell: bash
      run: go mod download
