name: GolangCI Lint
description: Run golangci-lint using action
inputs:
  version:
    description: Version of golangci-lint to use
    required: false
    default: v2.0.1

  config:
    description: Path to .golangci.yml config
    required: false
    default: .golangci.yml

runs:
  using: "composite"
  steps:
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6.0.1
      with:
        version: ${{ inputs.version }}
        args: --config=${{ inputs.config }}
