name: Go CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-go

      - name: Build
        run: |
          go mod download
          go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-go

      - name: Test with race detector
        run: go test -v -race ./...

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-go

      - name: Coverage
        run: |
          mkdir -p coverage
          go test -coverprofile=coverage/coverage.out ./...
          go tool cover -func=coverage/coverage.out

          COVERAGE=$(go tool cover -func=coverage/coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          THRESHOLD=80
          echo "Total coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "FAILURE: Code coverage is below the minimum threshold of $THRESHOLD%"
            exit 1
          fi

